#!/bin/bash

mkdir -p {$DIR_AUTORIDADES,$DIR_BUNDLE,$DIR_CA_ATIVA,$DIR_EMITIDOS,$DIR_PROCESSADAS,$DIR_SOLICITACOES,$DIR_TEMPLATES,$DIR_USUARIOS,$DIR_LOG,$DIR_TEMPLATES_CSR}

chown -R www-data: {$DIR_AUTORIDADES,$DIR_BUNDLE,$DIR_CA_ATIVA,$DIR_EMITIDOS,$DIR_PROCESSADAS,$DIR_SOLICITACOES,$DIR_TEMPLATES,$DIR_USUARIOS,$DIR_LOG,$DIR_TEMPLATES_CSR}

chmod 775 {$DIR_AUTORIDADES,$DIR_BUNDLE,$DIR_CA_ATIVA,$DIR_EMITIDOS,$DIR_PROCESSADAS,$DIR_SOLICITACOES,$DIR_TEMPLATES,$DIR_USUARIOS,$DIR_LOG,$DIR_TEMPLATES_CSR}
